steps:
  - id: integration-test
    name: golang:latest
    entrypoint: bash
    args:
      - -c
      - |
        cp .env-test-template.yaml .env-test.yaml
        go test ./...
    secretEnv:
      - DB_PASSWORD
      - MAILJET_API_KEY
      - MAILJET_SECRET_KEY
      - SENDGRID_API_KEY
  - id: prepare-prod-env
    name: bash
    args: ['cp', '.env-prod-template.yaml', '.env-prod.yaml']
  - id: deploy-legacy-api
    name: gcr.io/cloud-builders/gcloud
    waitFor: ['prepare-prod-env']
    entrypoint: bash
    args:
      - -c
      - |
        gcloud functions deploy legacy-api --allow-unauthenticated \
          --entry-point CloudFunctionForFrontendWithNetlifyJWT --trigger-http \
          --region asia-southeast1 --runtime go116 --memory 128MB --timeout 15s \
          --update-labels service=legacy --max-instances 100 \
          --set-secrets DB_PASSWORD=db_password:latest,ENCRYPTION_KEY=encryption_key:latest \
          --env-vars-file .env-prod.yaml
  - id: deploy-legacy-api-secret
    name: gcr.io/cloud-builders/gcloud
    waitFor: ['prepare-prod-env']
    entrypoint: bash
    args:
      - -c
      - |
        gcloud functions deploy legacy-api-secret --allow-unauthenticated \
          --entry-point CloudFunctionForFrontendWithUserSecret --trigger-http \
          --region asia-southeast1 --runtime go116 --memory 128MB --timeout 15s \
          --update-labels service=legacy --max-instances 100 \
          --set-secrets DB_PASSWORD=db_password:latest,ENCRYPTION_KEY=encryption_key:latest \
          --env-vars-file .env-prod.yaml
  - id: deploy-legacy-api-scheduler
    name: gcr.io/cloud-builders/gcloud
    waitFor: ['prepare-prod-env']
    entrypoint: bash
    args:
      - -c
      - |
        gcloud functions deploy legacy-api-scheduler \
          --entry-point CloudFunctionForSchedulerWithStaticSecret --trigger-topic project-legacy-scheduler \
          --region asia-southeast1 --runtime go116 --memory 128MB --timeout 15s \
          --update-labels service=legacy --max-instances 100 \
          --set-secrets DB_PASSWORD=db_password:latest,STATIC_SECRET=static_secret:latest,ENCRYPTION_KEY=encryption_key:latest,MAILJET_API_KEY=mailjet_api_key:latest,MAILJET_SECRET_KEY=mailjet_secret_key:latest,SENDGRID_API_KEY=sendgrid_api_key:latest \
          --env-vars-file .env-prod.yaml
availableSecrets:
  secretManager:
    - versionName: projects/548884499300/secrets/db_password_tester/versions/latest
      env: DB_PASSWORD
    - versionName: projects/548884499300/secrets/mailjet_api_key/versions/latest
      env: MAILJET_API_KEY
    - versionName: projects/548884499300/secrets/mailjet_secret_key/versions/latest
      env: MAILJET_SECRET_KEY
    - versionName: projects/548884499300/secrets/sendgrid_api_key/versions/latest
      env: SENDGRID_API_KEY
