// Code generated by sqlc. DO NOT EDIT.

package data

import (
	"time"

	"github.com/google/uuid"
)

type Message struct {
	ID                   uuid.UUID
	CreatedAt            time.Time
	MessageContent       string
	EmailCreator         string
	EmailReceivers       []string
	InactivePeriodDays   int32
	ReminderIntervalDays int32
	IsActive             bool
	ExtensionSecret      string
	InactiveAt           time.Time
	NextReminderAt       time.Time
}
